feat: move allowlist from syft to sympc
OpenMined/SyMPC pull request #162
Opened 2021-05-10 21:38 UTC by danielorihuela

## Description
Move the allow list of operations over share tensors from pysyft to sympc.
Decouple list of methods from pysyft, giving the control to sympc.

Related to #155.
#155 can be closed when issue of pysyft is closed too.

## Affected Dependencies
PySyft.

## How has this been tested?
- I executed sympc related tests of pysyft.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A). No because I cannot
- [x] My changes are covered by tests

2021-05-10 22:52 UTC, gmuraru commented on src/sympc/__init__.py
> +allowed_operations_on_share_tensor = [
Q: Could you move this in the `tensor` folder and here expose this through the `__all__` variable?

2021-05-11 07:20 UTC, gmuraru requested changes
No, I think it makes sense here!

Could you rename this to ```allowed_external_api_share_tensor``` (or if you have a better name? - I think having `allowed_operation_on_share_tensor` might indicate to the user that we allow only `operations` --> which in my head translates to methods). We also allow the creation of remote instances, access attributes, etc. 

Could you only validate this with a test - it should

**LE**: Ahh..now that I see this - could you move the other "allowlist" here? (like the one for classes/modules)

2021-05-11 21:44 UTC, gmuraru commented
> > No, I think it makes sense here!
> > Could you rename this to `allowed_external_api_share_tensor` (or if you have a better name? - I think having `allowed_operation_on_share_tensor` might indicate to the user that we allow only `operations` --> which in my head translates to methods). We also allow the creation of remote instances, access attributes, etc.
> > Could you only validate this with a test - it should
> > **LE**: Ahh..now that I see this - could you move the other "allowlist" here? (like the one for classes/modules)
> 
> Okey, then the names would be:
> 
> * `allowed_external_api_share_tensor` (methods)
> * `allowed_external_api_modules` (modules)
> * `allowed_external_api_classes` (classes)
>   Also, should I put the classes and modules list in sympc/**init**.py ?
> 
> I do not have enough knowledge of the system, but I would like to raise a yellow flag. I understand that that this will give SyMPC control and eliminate the need of two PR. However, we should keep in mind some things for the future (maybe create new issues).
> 
> 1. There are some lines of the "operations allowlist" in which syft appear. `        ("sympc.store.CryptoStore.get_primitives_from_store", "syft.lib.python.List"),`. If SyMPC is going to be a standalone in the long run, we should keep that in mind.
> 2. I do not know if makes sense to have lists of allowed modules, classes and methods to be used from the outside. Should not the code itself handle the visibility of the different elements?

If we do this with the allowlist, is only to keep the logic separated between SyMPC and PySyft (what we do here should not impact PySyft and vice-versa -- that's why I was thinking to move "our" stuff from PySyft here).

I totally agree with you that the best scenario would be to don't have those lists, only that for the moment, those lists are used to call remote operations on different types (a thing that PySyft knows how to do it).

We also have chunks of code where we do `client.lib.python.List()` (in SyMPC code) -- we are again coupled with the Pysyft I think -- I am still thinking if we can remove this coupling in a "nice and clean way".

2021-05-12 12:43 UTC, danielorihuela commented
> Could you only validate this with a test - it should

What exactly should I test?

2021-05-12 17:16 UTC, gmuraru commented
> > Could you only validate this with a test - it should
> 
> What exactly should I test?

Ignore me! there should be no test for this since it would already be covered by our tests

2021-05-12 17:19 UTC, gmuraru commented on src/sympc/tensor/share_tensor.py
> +allowed_external_api_share_tensor = [
This needs to be split, right?

2021-05-12 17:20 UTC, gmuraru commented on src/sympc/tensor/share_tensor.py
> +allowed_external_api_share_tensor = [
Maybe we can put those in a folder named `api` and then have 3 lists like:
`
sympc.api.allowed_external_classes
sympc.api.allowed_external_attrs
sympc.api.allowed_external_modules
```
Approximately the same name you have in the Syft module

2021-05-12 17:21 UTC, gmuraru commented on src/sympc/tensor/__init__.py
> +    "allowed_external_api_share_tensor",
And we don't have any changes to this file

2021-05-12 17:21 UTC, gmuraru commented on src/sympc/__init__.py
> +allowed_external_api_modules = [
Those changes would be moved to ```sympc/tensor/api.py```

2021-05-12 18:29 UTC, danielorihuela commented on src/sympc/api.py
> +from . import store  # noqa: 401
Yeah sorry, I need to focus more.

2021-05-12 19:24 UTC, gmuraru commented on src/sympc/api.py
> +from . import store  # noqa: 401
No worries! You do an excellent job! :D

2021-05-12 19:40 UTC, danielorihuela commented on src/sympc/api.py
> +from . import store  # noqa: 401
Thanks!

2021-05-12 23:04 UTC, gmuraru approved these changes
LGTM

2021-05-12 23:04 UTC, merged