added tests and fixed GradPow, GradMatMul
OpenMined/SyMPC pull request #211
Opened 2021-06-03 17:28 UTC by aanurraj

## Description
this PR closes #210  #206 

## Affected Dependencies
None

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2021-06-04 14:58 UTC, gmuraru commented
Only add an exception for the case we use a "Y" which is not an integer - such that we make sure that the gradient is propagated only to the "X" variable.

2021-06-04 14:58 UTC, gmuraru requested changes
See comment

2021-06-04 16:19 UTC, LaRiffle approved these changes
🙌

2021-06-04 16:23 UTC, Syzygianinfern0 reviewed
Do we have support for tensor with `no_grad=True`?

2021-06-04 17:31 UTC, gmuraru commented
> Do we have support for tensor with `no_grad=True`?

I don't think we have

2021-06-04 17:32 UTC, gmuraru commented on tests/sympc/tensor/grad/grad_functions_test.py
> +    if isinstance(power, float):
MAYBE: Create a separate test to "test" the exception path. Each test should have a single logic to be tested.

2021-06-04 17:32 UTC, gmuraru requested changes
Check comment

2021-06-04 20:01 UTC, gmuraru commented on tests/sympc/tensor/grad/grad_functions_test.py
> +    if not isinstance(power, int):
Remove this line because we know they are not int

2021-06-05 03:31 UTC, Syzygianinfern0 approved these changes
🚀

2021-06-05 07:52 UTC, gmuraru approved these changes
LGTM!

2021-06-05 07:53 UTC, merged