Add sum as a static function
OpenMined/SyMPC pull request #250
Opened 2021-06-23 09:30 UTC by Syzygianinfern0

## Description
Add `torch.sum` equivalent. This is to support "reducing across dimensions" (as @aanurraj required it :stuck_out_tongue: )

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2021-06-23 09:52 UTC, kamathhrishi commented on src/sympc/tensor/static.py
> +def sum_share_tensor(
Could you extend this for RSTensor too?

2021-06-23 11:08 UTC, kamathhrishi commented on tests/sympc/tensor/static_test.py
> +    x_secret = torch.arange(12).view(2, 2, 3)
Add a step size something like 0.5 so that it represents decimal values too?

2021-06-23 15:41 UTC, gmuraru commented
Q: Why can't we use the ```GradSum``` from ```grad_functions.py```

2021-06-23 15:41 UTC, gmuraru requested changes
See question

2021-06-23 15:43 UTC, Syzygianinfern0 commented
> Q: Why can't we use the `GradSum` from `grad_functions.py`

Yes, I noticed the same after making the PR. Although, for some reason passing the dim arg to it does not work right. I am investigating it. 

(I should have marked this as WIP but forgot to :sweat_smile: )

2021-07-28 00:06 UTC, gmuraru commented
@Syzygianinfern0 could we close this?

2021-07-28 01:35 UTC, Syzygianinfern0 commented
> @Syzygianinfern0 could we close this?

Yep 😅

2021-07-28 01:35 UTC, closed without merging