Add codecov.yml file
OpenMined/SyMPC pull request #296
Opened 2021-08-06 12:08 UTC by shubhank-saxena

## Description
This PR fixes #214 

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2021-08-06 12:45 UTC, rasswanth-s commented
Hi @shubhank-saxena ,
I think adding `codecov.yml` also solves this issue #267 ,[Link](https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/) .  could do you simple change (in src or test files ,adding a new line or some minor change) so that the CI could run , and we could validate if `Codecov comments` on pull requests.

2021-08-06 13:02 UTC, shubhank-saxena commented
> Hi @shubhank-saxena ,
> I think adding `codecov.yml` also solves this issue #267 ,[Link](https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/) . could do you simple change (in src or test files ,adding a new line or some minor change) so that the CI could run , and we could validate if `Codecov comments` on pull requests.

Sure. Will do that right away!

2021-08-06 14:53 UTC, aanurraj requested changes

2021-08-06 14:53 UTC, aanurraj commented on .codecov.yml
> +  range: "70...100"
can you make it to above 90 % ?

2021-08-06 16:25 UTC, shubhank-saxena commented on .codecov.yml
> +  range: "70...100"
Done!

2021-08-07 14:04 UTC, rasswanth-s commented
@shubhank-saxena , I added a minor change to trigger the CI, we could go for merge, if codecov comments on PR after CI.

2021-08-08 07:10 UTC, aanurraj approved these changes
Looks good, lets see if it solves or issue :D

2021-08-08 07:10 UTC, merged