Add "*.txt" files in path for GH workflow.
OpenMined/SyMPC pull request #83
Opened 2021-03-12 18:47 UTC by RaghavPrabhakar66

## Description
Added "*.txt" files as a path in tests.yml to trigger the GH workflow.

## Affected Dependencies
None

## How has this been tested?
None

## Checklist
- [x ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2021-03-12 19:05 UTC, arturomf94 commented
Is this to trigger the workflow whenever there are changes in the requirments?

2021-03-12 19:25 UTC, arturomf94 requested changes
I think this is great but maybe it's better to make the file more explicit: 

i.e.

Have `requirements_dev.txt` / `requirements.txt` instead of `**.txt`.

Because I don't think we want to trigger the workflow if we change anything in the license, for instance.

2021-03-12 19:25 UTC, arturomf94 commented
> I think this is great but maybe it's better to make the file more explicit:
> 
> i.e.
> 
> Have `requirements_dev.txt` / `requirements.txt` instead of `**.txt`.
> 
> Because I don't think we want to trigger the workflow if we change anything in the license, for instance.

@gmuraru what do you think about this?

2021-03-12 20:02 UTC, RaghavPrabhakar66 commented
@gmuraru  arturomf94 I have another doubt, Issue #76 states that we remove all dependencies from `requirements.txt` and put them to `setup.cfg` and to remove `requirements.txt` from GA workflows. Isn't that issue in contradiction to this one?

2021-03-12 20:35 UTC, arturomf94 commented
> @gmuraru @arturomf94 I have another doubt, Issue #76 states that we remove all dependencies from `requirements.txt` and put them to `setup.cfg` and to remove `requirements.txt` from GA workflows. Isn't that issue in contradiction to this one?

That's a good point! 🤔 @gmuraru?

2021-03-13 12:54 UTC, gmuraru commented
There is also another requirement file named ```requirements_dev.txt```.
Ideally, we would leave only the ```setup.cfg``` needed for installing sympc and the ```requirements_dev.txt``` would be used to install the devs stuff.

2021-03-13 20:02 UTC, arturomf94 commented
@RaghavPrabhakar66 - I think, for now, let's add both files explicitly: requirements_dev.txt and requirements.txt :+1:

2021-03-14 08:17 UTC, RaghavPrabhakar66 commented
@gmuraru @arturomf94 I have both requirements.txt to GA path.

2021-03-14 10:44 UTC, gmuraru commented on .github/workflows/tests.yml
> +      - "**.txt"
Q: Could you also change it here?

2021-03-14 14:21 UTC, RaghavPrabhakar66 commented on .github/workflows/tests.yml
> +      - "**.txt"
Done.

2021-03-14 15:40 UTC, arturomf94 commented
Thank you @RaghavPrabhakar66. This looks great IMO. Unfortunately, the tests are currently failing but I believe it has nothing to do with your changes. I think it's best if we try to wait until these problems are fixed anyway and we could merge after that.

2021-03-14 19:59 UTC, arturomf94 commented
Hm... That's really weird. I don't know what could be going on here. @gmuraru - any ideas?

2021-03-14 20:01 UTC, gmuraru commented
> Hm... That's really weird. I don't know what could be going on here. @gmuraru - any ideas?

I re-run the tests now to see if it something that happens only sometimes (we should open a ticket if that is the case)

2021-03-14 21:34 UTC, gmuraru approved these changes
LGTM! We need to keep an eye on that tolerance tests

2021-03-14 23:15 UTC, arturomf94 approved these changes
:)

2021-03-15 11:09 UTC, merged